#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [7]:
my_vec = np.zeros(10)

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [8]:
my_vec[4] = 1
my_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [14]:
np.reshape(np.arange(0,9),[3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [15]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [20]:
3 * 3 * 3 

27

In [25]:
np.reshape(np.random.random(27),[3,3,3])

array([[[0.42507076, 0.063062  , 0.36129731],
        [0.71840247, 0.25770052, 0.20561384],
        [0.73278914, 0.92283797, 0.03848503]],

       [[0.19985889, 0.90234607, 0.4998636 ],
        [0.21688012, 0.30523732, 0.00499948],
        [0.28672346, 0.35924472, 0.755596  ]],

       [[0.52865268, 0.20309465, 0.69404379],
        [0.38804981, 0.89932643, 0.42086536],
        [0.62639182, 0.931429  , 0.10153891]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [60]:
my_matrix = np.reshape(np.random.random(100), [10,10])

print('min is 'f'{my_matrix.min()}')
print('max is 'f'{my_matrix.max()}')

min is 0.002981458836946671
max is 0.9899655145413222


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [56]:
(np.random.random(30)).mean()

0.4471814708402161

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [77]:
a = np.arange(5)
m = np.reshape(np.concatenate((a,a,a,a,a)),[5,5])
m.transpose()

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [84]:
mtx = np.reshape(np.random.random(25),[5,5])
mtx
(mtx - mtx.mean())/np.std(mtx)

array([[-1.35764466, -0.04820776,  0.51462983,  0.79789279, -0.75713218],
       [ 1.15503315, -0.26517076,  0.25643887, -1.12296142,  0.63159447],
       [ 1.10271159, -1.60229423,  1.05657776, -1.76054019,  1.11205763],
       [ 0.88815804, -0.89647923,  0.91020122,  0.37749958, -0.96641588],
       [-0.81296072,  0.67104138, -1.71719291,  0.72146671,  1.11169693]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [89]:
np.intersect1d([1,2,3,6], [3,4,5,6])

array([3, 6])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [100]:
M = np.random.random(10)
M.sort()
M

array([0.1721085 , 0.18324899, 0.29192258, 0.31594911, 0.34959576,
       0.45863984, 0.62561829, 0.84775269, 0.85427294, 0.9643052 ])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [103]:
S = np.random.random(10)
S

array([0.6923929 , 0.94365141, 0.64579929, 0.26664613, 0.53330479,
       0.32377381, 0.12246096, 0.75305069, 0.80638949, 0.83641108])

In [104]:
np.argmax(S)

1

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [110]:
G = np.eye(3)
G - np.mean(G, axis = 0, keepdims = True)

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [137]:
Y = np.random.randint(0, 15, 15).reshape(5,3)
Y

array([[ 3,  5,  2],
       [ 8,  2,  2],
       [ 3,  4,  6],
       [ 2,  4,  1],
       [11,  7, 13]])

In [141]:
Y[np.where(Y > 4)]

array([ 5,  8,  6, 11,  7, 13])